//! Synthetic packet and playback workloads, independent of game protobufs.

use pbdems2::demo::{COMPRESSED_FLAG, CommandFrame, HEADER_SIZE, MAGIC, command};
use pbdems2::entity::{ClassEntry, CreateStringTable, PacketEntities};
use pbdems2::{CheckpointAdapter, CommandContext, DemoAdapter, Error, Result};

use crate::{
    BENCH_CLASS, BENCH_PROFILE, BitWriter, bool_serializer, packet_entity_creates,
    packet_entity_updates,
};

/// Deterministic bytes with little repetition, useful alongside compressible input.
pub fn varied_bytes(size: usize) -> Vec<u8> {
    let mut state = 0x1234_5678_u32;
    (0..size)
        .map(|_| {
            state ^= state << 13;
            state ^= state >> 17;
            state ^= state << 5;
            state as u8
        })
        .collect()
}

fn push_varint(mut value: u32, output: &mut Vec<u8>) {
    loop {
        let byte = (value & 0x7f) as u8;
        value >>= 7;
        output.push(byte | if value == 0 { 0 } else { 0x80 });
        if value == 0 {
            break;
        }
    }
}

fn push_command(output: &mut Vec<u8>, cmd: i32, tick: i32, body: &[u8], compressed: bool) {
    let encoded;
    let body = if compressed {
        encoded = snap::raw::Encoder::new()
            .compress_vec(body)
            .expect("valid input");
        &encoded
    } else {
        body
    };
    push_varint(
        cmd as u32 | if compressed { COMPRESSED_FLAG } else { 0 },
        output,
    );
    push_varint(tick as u32, output);
    push_varint(u32::try_from(body.len()).expect("fixture fits u32"), output);
    output.extend_from_slice(body);
}

fn demo_header() -> Vec<u8> {
    let mut bytes = MAGIC.to_vec();
    bytes.resize(HEADER_SIZE, 0);
    bytes
}

/// Outer framing workload with a sync tick, periodic keyframes, and a stop.
pub fn framing_demo(commands: usize, body_size: usize, compressed: bool) -> Vec<u8> {
    let mut bytes = demo_header();
    let body = varied_bytes(body_size);
    push_command(&mut bytes, command::SYNC_TICK, 0, &[], false);
    for tick in 1..=commands {
        let cmd = if tick.is_multiple_of(64) {
            command::FULL_PACKET
        } else {
            command::PACKET
        };
        push_command(&mut bytes, cmd, tick as i32, &body, compressed);
    }
    push_command(&mut bytes, command::STOP, commands as i32 + 1, &[], false);
    bytes
}

/// Packet framing that exercises every ubitvar width and multiple bit alignments.
pub fn packet_messages(count: usize, payload_size: usize) -> Vec<u8> {
    let mut writer = BitWriter::default();
    let payload = varied_bytes(payload_size);
    for index in 0..count {
        writer.push_ubitvar([7, 42, 513, 8192][index % 4]);
        writer.push_uvarint32(payload_size as u32);
        for &byte in &payload {
            writer.push_bits(u64::from(byte), 8);
        }
    }
    writer.finish()
}

/// Table fixture with prefix-compressed names and variable-size user data.
///
/// Every entry after the first references the preceding name's six-byte prefix.
pub fn table_with_user_data(
    count: usize,
    payload_size: usize,
    compressed: bool,
) -> CreateStringTable {
    let mut writer = BitWriter::default();
    let payload = vec![0x5a; payload_size];
    let encoded = if compressed {
        snap::raw::Encoder::new()
            .compress_vec(&payload)
            .expect("valid payload")
    } else {
        payload
    };
    for index in 0..count {
        writer.push_bool(true); // sequential index
        writer.push_bool(true); // key present
        writer.push_bool(index != 0); // history reference
        let suffix = if index == 0 {
            format!("entry-{index:05}")
        } else {
            writer.push_bits(index.saturating_sub(1).min(31) as u64, 5);
            writer.push_bits(6, 5);
            format!("{index:05}")
        };
        for byte in suffix.bytes().chain([0]) {
            writer.push_bits(u64::from(byte), 8);
        }
        writer.push_bool(true); // user data present
        writer.push_bool(compressed);
        writer.push_bits(encoded.len() as u64, 17);
        for &byte in &encoded {
            writer.push_bits(u64::from(byte), 8);
        }
    }
    CreateStringTable::new("payloads", count as i32, writer.finish()).with_flags(1)
}

/// Minimal adapter for measuring the neutral playback and entity layers.
///
/// Its command bodies are raw entity deltas. It deliberately does not include
/// game-specific protobuf decoding or dataset construction.
#[derive(Clone, Copy)]
pub struct PlaybackAdapter {
    entities: usize,
    fields: usize,
}

impl PlaybackAdapter {
    /// Match a fixture generated by [playback_demo].
    pub const fn new(entities: usize, fields: usize) -> Self {
        Self { entities, fields }
    }
}

impl DemoAdapter for PlaybackAdapter {
    type Error = Error;

    fn handle_command(
        &mut self,
        frame: &CommandFrame<'_>,
        body: &[u8],
        context: &mut CommandContext<'_, '_>,
    ) -> Result<()> {
        match frame.header().cmd {
            command::SEND_TABLES => {
                context.install_serializers(bool_serializer(self.fields), BENCH_PROFILE)
            }
            command::CLASS_INFO => {
                context.install_class_info([ClassEntry::new(0, BENCH_CLASS, BENCH_CLASS)])
            }
            command::SIGNON_PACKET | command::PACKET | command::FULL_PACKET => {
                context.apply_packet_entities(PacketEntities::new(self.entities as i32, body, 0))
            }
            _ => Ok(()),
        }
    }
}

impl CheckpointAdapter for PlaybackAdapter {
    type Checkpoint = Self;

    fn checkpoint(&self) -> Self {
        *self
    }

    fn from_checkpoint(checkpoint: &Self) -> Self {
        *checkpoint
    }
}

/// A complete neutral playback workload with populated signon and seek keyframes.
pub fn playback_demo(entities: usize, fields: usize, ticks: usize, compressed: bool) -> Vec<u8> {
    let mut bytes = demo_header();
    push_command(&mut bytes, command::SEND_TABLES, -1, &[], false);
    push_command(&mut bytes, command::CLASS_INFO, -1, &[], false);
    let creates = packet_entity_creates(entities, fields);
    let updates = packet_entity_updates(entities, fields);
    push_command(&mut bytes, command::SIGNON_PACKET, -1, &creates, compressed);
    push_command(&mut bytes, command::SYNC_TICK, 0, &[], false);
    for tick in 1..=ticks {
        let keyframe = tick.is_multiple_of(16);
        push_command(
            &mut bytes,
            if keyframe {
                command::FULL_PACKET
            } else {
                command::PACKET
            },
            tick as i32,
            if keyframe { &creates } else { &updates },
            compressed,
        );
    }
    push_command(&mut bytes, command::STOP, ticks as i32 + 1, &[], false);
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;
    use pbdems2::demo::Demo;
    use pbdems2::entity::StringTableContainer;
    use pbdems2::{DemoParser, PacketMessageIter};

    #[test]
    fn packet_fixture_preserves_payloads_across_alignments_and_varint_widths() {
        for size in [0, 16, 256, 4096] {
            let bytes = packet_messages(8, size);
            let expected = varied_bytes(size);
            let mut scratch = Vec::new();
            let frames: Vec<_> = PacketMessageIter::new(&bytes)
                .collect::<Result<_>>()
                .unwrap();
            assert_eq!(frames.len(), 8);
            assert!(frames.iter().any(|f| f.payload().is_none()));
            assert!(frames.iter().any(|f| f.payload().is_some()));
            for (index, frame) in frames.iter().enumerate() {
                assert_eq!(frame.message_type(), [7, 42, 513, 8192][index % 4]);
                assert_eq!(frame.payload_or_copy(&mut scratch).unwrap(), expected);
            }
        }
    }

    #[test]
    fn table_fixture_decodes_history_wrap_and_compressed_user_data() {
        for compressed in [false, true] {
            let mut tables = StringTableContainer::new();
            tables
                .handle_create(table_with_user_data(65, 64, compressed))
                .unwrap();
            for (index, entry) in tables
                .find_table("payloads")
                .unwrap()
                .entries()
                .iter()
                .enumerate()
            {
                assert_eq!(
                    entry.string.as_deref(),
                    Some(format!("entry-{index:05}").as_str())
                );
                assert_eq!(entry.user_data.as_deref(), Some([0x5a; 64].as_slice()));
            }
        }
    }

    #[test]
    fn framing_fixture_round_trips_bodies_and_indexes_keyframes() {
        for compressed in [false, true] {
            let bytes = framing_demo(128, 256, compressed);
            let demo = Demo::new(&bytes).unwrap();
            let mut scratch = Vec::new();
            let expected = varied_bytes(256);
            assert_eq!(demo.index().unwrap().full_packets().len(), 2);
            let mut packets = 0;
            for frame in demo.commands() {
                let frame = frame.unwrap();
                if matches!(frame.header().cmd, command::PACKET | command::FULL_PACKET) {
                    frame.decode_body(&mut scratch).unwrap();
                    assert_eq!(scratch, expected);
                    packets += 1;
                }
            }
            assert_eq!(packets, 128);
        }
    }

    #[test]
    fn playback_fixture_matches_fresh_prepared_and_seek_results() {
        for compressed in [false, true] {
            let bytes = playback_demo(8, 4, 32, compressed);
            let parser = DemoParser::new(&bytes).unwrap();
            let adapter = PlaybackAdapter::new(8, 4);
            let prepared = parser.prepare(adapter, 1.0 / 64.0).unwrap();
            let mut changes = 0;
            let mut fresh_adapter = adapter;
            let fresh = parser
                .run_to_end(&mut fresh_adapter, 1.0 / 64.0, |state| {
                    changes += state.entities().entity_changes().len();
                })
                .unwrap();
            assert_eq!(changes, 8 * 32 + 8 * 2); // create keyframes also delete old slots
            let replay = prepared
                .session(parser)
                .unwrap()
                .run_to_end(|_| {})
                .unwrap();
            let seek = prepared.session(parser).unwrap().parse_to_tick(30).unwrap();
            assert_eq!(fresh.tick(), 33);
            assert_eq!(replay.tick(), fresh.tick());
            assert_eq!(seek.tick(), 30);
            for index in 0..8 {
                for state in [&fresh, &replay, &seek] {
                    let entity = state.entities().get(index).unwrap();
                    assert_eq!(entity.fields.len(), 4);
                    for field_index in 0..4 {
                        let key = state
                            .serializers()
                            .get(BENCH_CLASS)
                            .unwrap()
                            .resolve_field_key(&format!("m_bField{field_index}"))
                            .unwrap();
                        assert!(matches!(entity.field_value(Some(key)),
                            Some(pbdems2::entity::FieldValue::Bool(value)) if *value == (field_index % 3 == 0)));
                    }
                }
            }
        }
    }
}
