[package]
name = "pbdems2-fuzz"
version = "0.0.0"
publish = false
edition = "2024"
rust-version = "1.88.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
pbdems2 = { path = "..", default-features = false }

[[bin]]
name = "command_stream"
path = "fuzz_targets/command_stream.rs"
test = false
doc = false
bench = false

[[bin]]
name = "bitreader"
path = "fuzz_targets/bitreader.rs"
test = false
doc = false
bench = false

[[bin]]
name = "field_paths"
path = "fuzz_targets/field_paths.rs"
test = false
doc = false
bench = false

[[bin]]
name = "serializers"
path = "fuzz_targets/serializers.rs"
test = false
doc = false
bench = false

[[bin]]
name = "string_tables"
path = "fuzz_targets/string_tables.rs"
test = false
doc = false
bench = false

[[bin]]
name = "packet_entities"
path = "fuzz_targets/packet_entities.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fuzzing)"] }
