[package]
name = "awpy-profile-extension"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "_awpy"
crate-type = ["cdylib"]
path = "../../../../../awpy-github/awpy/crates/awpy-python/src/lib.rs"

[dependencies]
awpy.workspace = true
awpy-proto.workspace = true
prost.workspace = true
pyo3.workspace = true
pyo3-polars.workspace = true
polars = { workspace = true, features = ["dtype-full"] }
